#ifndef INTELLIGENTDESIGNDLL_GLOBAL_H
#define INTELLIGENTDESIGNDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INTELLIGENTDESIGNDLL_LIBRARY)
#  define INTELLIGENTDESIGNDLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define INTELLIGENTDESIGNDLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // INTELLIGENTDESIGNDLL_GLOBAL_H
